Сделал 4 модуль
js-tasks-ru/jsbasic-20230116-2_keir548 pull request #5
Opened 2023-02-12 10:39 UTC by NZeroName

2023-02-12 10:40 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-12 10:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-12 13:56 UTC, SinimaWath requested changes

2023-02-12 13:56 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  if(!isNaN(elem)){
А зачем тут проверка на isNaN - elem - это у тебя dom element, и он никогда не может быть NaN, только null или DOM обьект

2023-02-13 17:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-15 15:50 UTC, NZeroName commented
Исправил и добавил 5 модуль

2023-02-16 09:58 UTC, SinimaWath approved these changes

2023-02-16 09:59 UTC, merged